- name: create /etc/admin dir 
  sudo: True
  file: path=/etc/admin state=directory

- name: copy www dir
  sudo: True
  copy: src=www dest=/var/ owner=pi group=pi

- name: put config file in place
  sudo: True
  copy: src=files/etc/admin/settings.yaml dest=/etc/admin/settings.yaml owner=pi group=pi mode=644

 
- name: install required packages 
  apt: pkg={{ item }} state=installed update_cache=yes 
  with_items: 
  - python-yaml
