- name: Update package cache 
  shell: apt-get update 

- name: Upgrade all packages 
  shell: DEBIAN_FRONTEND=noninteractive apt-get -y --assume-yes dist-upgrade  

- name: get python-apt 
  shell: DEBIAN_FRONTEND=noninteractive apt-get -y install python-apt; touch /root/.python-apt-done
    creates=/root/.python-apt-done 

- name: install required packages 
  apt: pkg={{ item }} state=installed update_cache=yes 
  with_items: 
  - unclutter  
  - lockfile-progs  
  - systemd  
  - git  
  - vim  
  - telnet
  - unzip
  - screen
  - python-pip
  - python-dev
  - python-paramiko
  - python-yaml
  - virtualenvwrapper
  - iw
  - sl
  - htop
  - tshark
  - subversion
  - firmware-realtek
  - libnl-dev
  - libssl-dev
  - hostapd
  - nfs-common 
  - postfix

