- name: put vimrc in place 
  sudo: True
  copy: src=files/root/vimrc dest=/root/.vimrc

- name: put vim dir in place
  copy: src=files/root/vim dest=/root/.vim

- name: put vimrc in place 
  sudo: True
  copy: src=files/root/vimrc dest=/home/pi/.vimrc

- name: put vim dir in place
  copy: src=files/root/vim dest=/home/pi/.vim
