- name: install required packages 
  apt: pkg={{ item }} state=installed update_cache=yes 
  with_items: 
  - gettext 
  - make 
  - intltool 
  - build-essential 
  - automake 
  - autoconf 
  - uuid 
  - uuid-dev 
  - dos2unix 
  - curl
  - gcc-4.7
  - g++-4.7
  - dnsmasq
  - hostapd
  - libssl-dev

- name: Remove packages
  apt: pkg={{ item }} state=absent update_cache=yes 
  with_items: 
  - ifplugd

- name: Turn on ssh at boot time 
  sudo: True
  shell: update-rc.d {{ item }} defaults
  with_item:
  - ssh 
  - ntp

- name: Put aircrack ng installer script in place
  sudo: True
  copy: src=scripts/install-aircrack-ng.sh dest=/root/bin/install-aircrack-ng.sh mode=700 group=pi owner=pi

- name: Install aircrack NG
  sudo: True
  shell: /root/bin/install-aircrack-ng.sh

- name: Setup GCC 4.7
  sudo: True
  shell: update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.7 40 --slave /usr/bin/g++ g++ /usr/bin/g++-4.7

- name: Get fruity wifi repository and move into place
  sudo: False
  git: repo=https://github.com/fliphess/FruityWifi.git dest=/tmp/FruityWifi update=yes accept_hostkey=yes

- name: Move fruity in place
  sudo: True
  shell: rm -rf /usr/share/FruityWifi && sudo mv -f /tmp/FruityWifi/FruityWifi /usr/share

- name: Create symlink to www
  sudo: True
  file: src=/usr/share/FruityWifi/www dest=/var/www/FruityWifi state=link owner=root group=root

- name: create symlink to logs
  sudo: True
  file: src=/usr/share/FruityWifi/logs dest=/var/www/FruityWifi/logs state=link owner=root group=root

- name: Create symlink to /usr/share/FruityWifi/www.site
  sudo: True
  file: src=/usr/share/FruityWifi/www.site dest=/var/www/site state=link 

- name: Create temp dir  
  sudo: True
  file: path=/var/www/tmp state=directory owner=pi group=pi mode=777

- name: Set permissions to /usr/share/FruityWifi/squid.inject/poison.pl 
  sudo: True
  file: path=/usr/share/FruityWifi/squid.inject/poison.pl mode=755 

- name: Set permissions to /usr/share/FruityWifi/www.site/data.txt
  sudo: True
  file: path=/usr/share/FruityWifi/www.site/data.txt mode=777 

- name: Set perms to /usr/share/FruityWifi/www.site/inject/data.txt
  sudo: True
  file: path=/usr/share/FruityWifi/www.site/inject/data.txt mode=777

- name: Recursive chown /usr/share/FruityWifi/www.site
  sudo: True
  file: path=/usr/share/FruityWifi/www.site owner=pi group=pi recurse=yes

- name: Build Danger script
  sudo: True
  shell: cd /usr/share/FruityWifi/bin/ && sudo gcc danger.c -o danger

- name: Perms Danger script 
  sudo: True
  file: path=/usr/share/FruityWifi/bin/danger mode=4755 

- name: update fruity wifi modules
  sudo: True
  shell: /tmp/FruityWifi/install-modules.py       
